//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientGaji.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="jabatanview", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGaji")]
    [System.SerializableAttribute()]
    public partial class jabatanview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gajipokokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idjabatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jabatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tjjabatanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gajipokok {
            get {
                return this.gajipokokField;
            }
            set {
                if ((this.gajipokokField.Equals(value) != true)) {
                    this.gajipokokField = value;
                    this.RaisePropertyChanged("gajipokok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idjabatan {
            get {
                return this.idjabatanField;
            }
            set {
                if ((this.idjabatanField.Equals(value) != true)) {
                    this.idjabatanField = value;
                    this.RaisePropertyChanged("idjabatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jabatan {
            get {
                return this.jabatanField;
            }
            set {
                if ((object.ReferenceEquals(this.jabatanField, value) != true)) {
                    this.jabatanField = value;
                    this.RaisePropertyChanged("jabatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tjjabatan {
            get {
                return this.tjjabatanField;
            }
            set {
                if ((this.tjjabatanField.Equals(value) != true)) {
                    this.tjjabatanField = value;
                    this.RaisePropertyChanged("tjjabatan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Golongan", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGaji")]
    [System.SerializableAttribute()]
    public partial class Golongan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int golonganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idgolonganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tjkeluargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tjkesehatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uanglemburField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uangmakanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int golongan {
            get {
                return this.golonganField;
            }
            set {
                if ((this.golonganField.Equals(value) != true)) {
                    this.golonganField = value;
                    this.RaisePropertyChanged("golongan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idgolongan {
            get {
                return this.idgolonganField;
            }
            set {
                if ((this.idgolonganField.Equals(value) != true)) {
                    this.idgolonganField = value;
                    this.RaisePropertyChanged("idgolongan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tjkeluarga {
            get {
                return this.tjkeluargaField;
            }
            set {
                if ((this.tjkeluargaField.Equals(value) != true)) {
                    this.tjkeluargaField = value;
                    this.RaisePropertyChanged("tjkeluarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tjkesehatan {
            get {
                return this.tjkesehatanField;
            }
            set {
                if ((this.tjkesehatanField.Equals(value) != true)) {
                    this.tjkesehatanField = value;
                    this.RaisePropertyChanged("tjkesehatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uanglembur {
            get {
                return this.uanglemburField;
            }
            set {
                if ((this.uanglemburField.Equals(value) != true)) {
                    this.uanglemburField = value;
                    this.RaisePropertyChanged("uanglembur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uangmakan {
            get {
                return this.uangmakanField;
            }
            set {
                if ((this.uangmakanField.Equals(value) != true)) {
                    this.uangmakanField = value;
                    this.RaisePropertyChanged("uangmakan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Karyawan", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGaji")]
    [System.SerializableAttribute()]
    public partial class Karyawan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idgolonganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idjabatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idkaryawanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jeniskelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat {
            get {
                return this.alamatField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatField, value) != true)) {
                    this.alamatField = value;
                    this.RaisePropertyChanged("alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idgolongan {
            get {
                return this.idgolonganField;
            }
            set {
                if ((this.idgolonganField.Equals(value) != true)) {
                    this.idgolonganField = value;
                    this.RaisePropertyChanged("idgolongan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idjabatan {
            get {
                return this.idjabatanField;
            }
            set {
                if ((this.idjabatanField.Equals(value) != true)) {
                    this.idjabatanField = value;
                    this.RaisePropertyChanged("idjabatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idkaryawan {
            get {
                return this.idkaryawanField;
            }
            set {
                if ((this.idkaryawanField.Equals(value) != true)) {
                    this.idkaryawanField = value;
                    this.RaisePropertyChanged("idkaryawan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jeniskelamin {
            get {
                return this.jeniskelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.jeniskelaminField, value) != true)) {
                    this.jeniskelaminField = value;
                    this.RaisePropertyChanged("jeniskelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nip {
            get {
                return this.nipField;
            }
            set {
                if ((this.nipField.Equals(value) != true)) {
                    this.nipField = value;
                    this.RaisePropertyChanged("nip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hadir", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGaji")]
    [System.SerializableAttribute()]
    public partial class Hadir : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bulanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idhadirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idkaryawanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lemburField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int masukField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bulan {
            get {
                return this.bulanField;
            }
            set {
                if ((object.ReferenceEquals(this.bulanField, value) != true)) {
                    this.bulanField = value;
                    this.RaisePropertyChanged("bulan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idhadir {
            get {
                return this.idhadirField;
            }
            set {
                if ((this.idhadirField.Equals(value) != true)) {
                    this.idhadirField = value;
                    this.RaisePropertyChanged("idhadir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idkaryawan {
            get {
                return this.idkaryawanField;
            }
            set {
                if ((this.idkaryawanField.Equals(value) != true)) {
                    this.idkaryawanField = value;
                    this.RaisePropertyChanged("idkaryawan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lembur {
            get {
                return this.lemburField;
            }
            set {
                if ((this.lemburField.Equals(value) != true)) {
                    this.lemburField = value;
                    this.RaisePropertyChanged("lembur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int masuk {
            get {
                return this.masukField;
            }
            set {
                if ((this.masukField.Equals(value) != true)) {
                    this.masukField = value;
                    this.RaisePropertyChanged("masuk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gajisub", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGaji")]
    [System.SerializableAttribute()]
    public partial class Gajisub : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int subtotField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int subtot {
            get {
                return this.subtotField;
            }
            set {
                if ((this.subtotField.Equals(value) != true)) {
                    this.subtotField = value;
                    this.RaisePropertyChanged("subtot");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="gajiview", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGaji")]
    [System.SerializableAttribute()]
    public partial class gajiview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idgajiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idhadirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int noslipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pphField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int subtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tanggalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idgaji {
            get {
                return this.idgajiField;
            }
            set {
                if ((this.idgajiField.Equals(value) != true)) {
                    this.idgajiField = value;
                    this.RaisePropertyChanged("idgaji");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idhadir {
            get {
                return this.idhadirField;
            }
            set {
                if ((this.idhadirField.Equals(value) != true)) {
                    this.idhadirField = value;
                    this.RaisePropertyChanged("idhadir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int noslip {
            get {
                return this.noslipField;
            }
            set {
                if ((this.noslipField.Equals(value) != true)) {
                    this.noslipField = value;
                    this.RaisePropertyChanged("noslip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pph {
            get {
                return this.pphField;
            }
            set {
                if ((this.pphField.Equals(value) != true)) {
                    this.pphField = value;
                    this.RaisePropertyChanged("pph");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int subtotal {
            get {
                return this.subtotalField;
            }
            set {
                if ((this.subtotalField.Equals(value) != true)) {
                    this.subtotalField = value;
                    this.RaisePropertyChanged("subtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tanggal {
            get {
                return this.tanggalField;
            }
            set {
                if ((this.tanggalField.Equals(value) != true)) {
                    this.tanggalField = value;
                    this.RaisePropertyChanged("tanggal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gaji", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGaji")]
    [System.SerializableAttribute()]
    public partial class Gaji : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bulanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gajipokokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int golonganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jabatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lemburField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int masukField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int noslipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pphField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int subtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tanggalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tjjabatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tjkeluargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tjkesehatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uanglemburField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uangmakanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bulan {
            get {
                return this.bulanField;
            }
            set {
                if ((object.ReferenceEquals(this.bulanField, value) != true)) {
                    this.bulanField = value;
                    this.RaisePropertyChanged("bulan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gajipokok {
            get {
                return this.gajipokokField;
            }
            set {
                if ((this.gajipokokField.Equals(value) != true)) {
                    this.gajipokokField = value;
                    this.RaisePropertyChanged("gajipokok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int golongan {
            get {
                return this.golonganField;
            }
            set {
                if ((this.golonganField.Equals(value) != true)) {
                    this.golonganField = value;
                    this.RaisePropertyChanged("golongan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jabatan {
            get {
                return this.jabatanField;
            }
            set {
                if ((object.ReferenceEquals(this.jabatanField, value) != true)) {
                    this.jabatanField = value;
                    this.RaisePropertyChanged("jabatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lembur {
            get {
                return this.lemburField;
            }
            set {
                if ((this.lemburField.Equals(value) != true)) {
                    this.lemburField = value;
                    this.RaisePropertyChanged("lembur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int masuk {
            get {
                return this.masukField;
            }
            set {
                if ((this.masukField.Equals(value) != true)) {
                    this.masukField = value;
                    this.RaisePropertyChanged("masuk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nip {
            get {
                return this.nipField;
            }
            set {
                if ((this.nipField.Equals(value) != true)) {
                    this.nipField = value;
                    this.RaisePropertyChanged("nip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int noslip {
            get {
                return this.noslipField;
            }
            set {
                if ((this.noslipField.Equals(value) != true)) {
                    this.noslipField = value;
                    this.RaisePropertyChanged("noslip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pph {
            get {
                return this.pphField;
            }
            set {
                if ((this.pphField.Equals(value) != true)) {
                    this.pphField = value;
                    this.RaisePropertyChanged("pph");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int subtotal {
            get {
                return this.subtotalField;
            }
            set {
                if ((this.subtotalField.Equals(value) != true)) {
                    this.subtotalField = value;
                    this.RaisePropertyChanged("subtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tanggal {
            get {
                return this.tanggalField;
            }
            set {
                if ((this.tanggalField.Equals(value) != true)) {
                    this.tanggalField = value;
                    this.RaisePropertyChanged("tanggal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tjjabatan {
            get {
                return this.tjjabatanField;
            }
            set {
                if ((this.tjjabatanField.Equals(value) != true)) {
                    this.tjjabatanField = value;
                    this.RaisePropertyChanged("tjjabatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tjkeluarga {
            get {
                return this.tjkeluargaField;
            }
            set {
                if ((this.tjkeluargaField.Equals(value) != true)) {
                    this.tjkeluargaField = value;
                    this.RaisePropertyChanged("tjkeluarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tjkesehatan {
            get {
                return this.tjkesehatanField;
            }
            set {
                if ((this.tjkesehatanField.Equals(value) != true)) {
                    this.tjkesehatanField = value;
                    this.RaisePropertyChanged("tjkesehatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uanglembur {
            get {
                return this.uanglemburField;
            }
            set {
                if ((this.uanglemburField.Equals(value) != true)) {
                    this.uanglemburField = value;
                    this.RaisePropertyChanged("uanglembur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uangmakan {
            get {
                return this.uangmakanField;
            }
            set {
                if ((this.uangmakanField.Equals(value) != true)) {
                    this.uangmakanField = value;
                    this.RaisePropertyChanged("uangmakan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="gajiviewall", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGaji")]
    [System.SerializableAttribute()]
    public partial class gajiviewall : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bulanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gajipokokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int golonganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jabatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lemburField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int masukField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int noslipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pphField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int subtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tanggalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tjjabatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tjkeluargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tjkesehatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uanglemburField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int uangmakanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bulan {
            get {
                return this.bulanField;
            }
            set {
                if ((object.ReferenceEquals(this.bulanField, value) != true)) {
                    this.bulanField = value;
                    this.RaisePropertyChanged("bulan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gajipokok {
            get {
                return this.gajipokokField;
            }
            set {
                if ((this.gajipokokField.Equals(value) != true)) {
                    this.gajipokokField = value;
                    this.RaisePropertyChanged("gajipokok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int golongan {
            get {
                return this.golonganField;
            }
            set {
                if ((this.golonganField.Equals(value) != true)) {
                    this.golonganField = value;
                    this.RaisePropertyChanged("golongan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jabatan {
            get {
                return this.jabatanField;
            }
            set {
                if ((object.ReferenceEquals(this.jabatanField, value) != true)) {
                    this.jabatanField = value;
                    this.RaisePropertyChanged("jabatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lembur {
            get {
                return this.lemburField;
            }
            set {
                if ((this.lemburField.Equals(value) != true)) {
                    this.lemburField = value;
                    this.RaisePropertyChanged("lembur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int masuk {
            get {
                return this.masukField;
            }
            set {
                if ((this.masukField.Equals(value) != true)) {
                    this.masukField = value;
                    this.RaisePropertyChanged("masuk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nip {
            get {
                return this.nipField;
            }
            set {
                if ((this.nipField.Equals(value) != true)) {
                    this.nipField = value;
                    this.RaisePropertyChanged("nip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int noslip {
            get {
                return this.noslipField;
            }
            set {
                if ((this.noslipField.Equals(value) != true)) {
                    this.noslipField = value;
                    this.RaisePropertyChanged("noslip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pph {
            get {
                return this.pphField;
            }
            set {
                if ((this.pphField.Equals(value) != true)) {
                    this.pphField = value;
                    this.RaisePropertyChanged("pph");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int subtotal {
            get {
                return this.subtotalField;
            }
            set {
                if ((this.subtotalField.Equals(value) != true)) {
                    this.subtotalField = value;
                    this.RaisePropertyChanged("subtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tanggal {
            get {
                return this.tanggalField;
            }
            set {
                if ((this.tanggalField.Equals(value) != true)) {
                    this.tanggalField = value;
                    this.RaisePropertyChanged("tanggal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tjjabatan {
            get {
                return this.tjjabatanField;
            }
            set {
                if ((this.tjjabatanField.Equals(value) != true)) {
                    this.tjjabatanField = value;
                    this.RaisePropertyChanged("tjjabatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tjkeluarga {
            get {
                return this.tjkeluargaField;
            }
            set {
                if ((this.tjkeluargaField.Equals(value) != true)) {
                    this.tjkeluargaField = value;
                    this.RaisePropertyChanged("tjkeluarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tjkesehatan {
            get {
                return this.tjkesehatanField;
            }
            set {
                if ((this.tjkesehatanField.Equals(value) != true)) {
                    this.tjkesehatanField = value;
                    this.RaisePropertyChanged("tjkesehatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uanglembur {
            get {
                return this.uanglemburField;
            }
            set {
                if ((this.uanglemburField.Equals(value) != true)) {
                    this.uanglemburField = value;
                    this.RaisePropertyChanged("uanglembur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uangmakan {
            get {
                return this.uangmakanField;
            }
            set {
                if ((this.uangmakanField.Equals(value) != true)) {
                    this.uangmakanField = value;
                    this.RaisePropertyChanged("uangmakan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataRegister", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGaji")]
    [System.SerializableAttribute()]
    public partial class DataRegister : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kategoriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string kategori {
            get {
                return this.kategoriField;
            }
            set {
                if ((object.ReferenceEquals(this.kategoriField, value) != true)) {
                    this.kategoriField = value;
                    this.RaisePropertyChanged("kategori");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/jabatan", ReplyAction="http://tempuri.org/IService1/jabatanResponse")]
        string jabatan(int idjabatan, [System.ServiceModel.MessageParameterAttribute(Name="jabatan")] string jabatan1, int gajipokok, int tjjabatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/jabatan", ReplyAction="http://tempuri.org/IService1/jabatanResponse")]
        System.Threading.Tasks.Task<string> jabatanAsync(int idjabatan, string jabatan, int gajipokok, int tjjabatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editjabatan", ReplyAction="http://tempuri.org/IService1/editjabatanResponse")]
        string editjabatan(int idjabatan, string jabatan, int gajipokok, int tjjabatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editjabatan", ReplyAction="http://tempuri.org/IService1/editjabatanResponse")]
        System.Threading.Tasks.Task<string> editjabatanAsync(int idjabatan, string jabatan, int gajipokok, int tjjabatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletejabatan", ReplyAction="http://tempuri.org/IService1/deletejabatanResponse")]
        string deletejabatan(int idjabatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletejabatan", ReplyAction="http://tempuri.org/IService1/deletejabatanResponse")]
        System.Threading.Tasks.Task<string> deletejabatanAsync(int idjabatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/jabatanview", ReplyAction="http://tempuri.org/IService1/jabatanviewResponse")]
        ClientGaji.ServiceReference1.jabatanview[] jabatanview();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/jabatanview", ReplyAction="http://tempuri.org/IService1/jabatanviewResponse")]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.jabatanview[]> jabatanviewAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/golongan", ReplyAction="http://tempuri.org/IService1/golonganResponse")]
        string golongan(int idgolongan, [System.ServiceModel.MessageParameterAttribute(Name="golongan")] int golongan1, int tjkeluarga, int tjkesehatan, int uanglembur, int uangmakan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/golongan", ReplyAction="http://tempuri.org/IService1/golonganResponse")]
        System.Threading.Tasks.Task<string> golonganAsync(int idgolongan, int golongan, int tjkeluarga, int tjkesehatan, int uanglembur, int uangmakan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editgolongan", ReplyAction="http://tempuri.org/IService1/editgolonganResponse")]
        string editgolongan(int idgolongan, int golongan, int tjkeluarga, int tjkesehatan, int uanglembur, int uangmakann);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editgolongan", ReplyAction="http://tempuri.org/IService1/editgolonganResponse")]
        System.Threading.Tasks.Task<string> editgolonganAsync(int idgolongan, int golongan, int tjkeluarga, int tjkesehatan, int uanglembur, int uangmakann);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletegolongan", ReplyAction="http://tempuri.org/IService1/deletegolonganResponse")]
        string deletegolongan(int idgolongan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletegolongan", ReplyAction="http://tempuri.org/IService1/deletegolonganResponse")]
        System.Threading.Tasks.Task<string> deletegolonganAsync(int idgolongan);
        
        // CODEGEN: Generating message contract since the wrapper name (Golongan) of message GolonganRequest does not match the default value (Golongan1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Golongan", ReplyAction="http://tempuri.org/IService1/GolonganResponse")]
        ClientGaji.ServiceReference1.GolonganResponse Golongan1(ClientGaji.ServiceReference1.GolonganRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Golongan", ReplyAction="http://tempuri.org/IService1/GolonganResponse")]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.GolonganResponse> Golongan1Async(ClientGaji.ServiceReference1.GolonganRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/karyawan", ReplyAction="http://tempuri.org/IService1/karyawanResponse")]
        string karyawan(int idkaryawan, int nip, string nama, string jeniskelamin, string alamat, int idjabatan, int idgolongan, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/karyawan", ReplyAction="http://tempuri.org/IService1/karyawanResponse")]
        System.Threading.Tasks.Task<string> karyawanAsync(int idkaryawan, int nip, string nama, string jeniskelamin, string alamat, int idjabatan, int idgolongan, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editkaryawan", ReplyAction="http://tempuri.org/IService1/editkaryawanResponse")]
        string editkaryawan(int idkaryawan, int nip, string nama, string jeniskelamin, string alamat, int idjabatan, int idgolongan, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editkaryawan", ReplyAction="http://tempuri.org/IService1/editkaryawanResponse")]
        System.Threading.Tasks.Task<string> editkaryawanAsync(int idkaryawan, int nip, string nama, string jeniskelamin, string alamat, int idjabatan, int idgolongan, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletekaryawan", ReplyAction="http://tempuri.org/IService1/deletekaryawanResponse")]
        string deletekaryawan(int idkaryawan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletekaryawan", ReplyAction="http://tempuri.org/IService1/deletekaryawanResponse")]
        System.Threading.Tasks.Task<string> deletekaryawanAsync(int idkaryawan);
        
        // CODEGEN: Generating message contract since the wrapper name (Karyawan) of message KaryawanRequest does not match the default value (Karyawan1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Karyawan", ReplyAction="http://tempuri.org/IService1/KaryawanResponse")]
        ClientGaji.ServiceReference1.KaryawanResponse Karyawan1(ClientGaji.ServiceReference1.KaryawanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Karyawan", ReplyAction="http://tempuri.org/IService1/KaryawanResponse")]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.KaryawanResponse> Karyawan1Async(ClientGaji.ServiceReference1.KaryawanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hadir", ReplyAction="http://tempuri.org/IService1/hadirResponse")]
        string hadir(int idhadir, string bulan, int idkaryawan, int lembur, int masuk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hadir", ReplyAction="http://tempuri.org/IService1/hadirResponse")]
        System.Threading.Tasks.Task<string> hadirAsync(int idhadir, string bulan, int idkaryawan, int lembur, int masuk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edithadir", ReplyAction="http://tempuri.org/IService1/edithadirResponse")]
        string edithadir(int idhadir, string bulan, int idkaryawan, int lembur, int masuk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edithadir", ReplyAction="http://tempuri.org/IService1/edithadirResponse")]
        System.Threading.Tasks.Task<string> edithadirAsync(int idhadir, string bulan, int idkaryawan, int lembur, int masuk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletehadir", ReplyAction="http://tempuri.org/IService1/deletehadirResponse")]
        string deletehadir(int idhadir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletehadir", ReplyAction="http://tempuri.org/IService1/deletehadirResponse")]
        System.Threading.Tasks.Task<string> deletehadirAsync(int idhadir);
        
        // CODEGEN: Generating message contract since the wrapper name (Hadir) of message HadirRequest does not match the default value (Hadir1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Hadir", ReplyAction="http://tempuri.org/IService1/HadirResponse")]
        ClientGaji.ServiceReference1.HadirResponse Hadir1(ClientGaji.ServiceReference1.HadirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Hadir", ReplyAction="http://tempuri.org/IService1/HadirResponse")]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.HadirResponse> Hadir1Async(ClientGaji.ServiceReference1.HadirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/gaji", ReplyAction="http://tempuri.org/IService1/gajiResponse")]
        string gaji(int noslip, System.DateTime tanggal, int idhadir, int subtotal, int pph);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/gaji", ReplyAction="http://tempuri.org/IService1/gajiResponse")]
        System.Threading.Tasks.Task<string> gajiAsync(int noslip, System.DateTime tanggal, int idhadir, int subtotal, int pph);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editgaji", ReplyAction="http://tempuri.org/IService1/editgajiResponse")]
        string editgaji(int idgaji, int noslip, System.DateTime tanggal, int idhadir, int subtotal, int pph);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editgaji", ReplyAction="http://tempuri.org/IService1/editgajiResponse")]
        System.Threading.Tasks.Task<string> editgajiAsync(int idgaji, int noslip, System.DateTime tanggal, int idhadir, int subtotal, int pph);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletegaji", ReplyAction="http://tempuri.org/IService1/deletegajiResponse")]
        string deletegaji(int noslip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletegaji", ReplyAction="http://tempuri.org/IService1/deletegajiResponse")]
        System.Threading.Tasks.Task<string> deletegajiAsync(int noslip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Gajisub", ReplyAction="http://tempuri.org/IService1/GajisubResponse")]
        ClientGaji.ServiceReference1.Gajisub[] Gajisub(int idhadir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Gajisub", ReplyAction="http://tempuri.org/IService1/GajisubResponse")]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.Gajisub[]> GajisubAsync(int idhadir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/gajiview", ReplyAction="http://tempuri.org/IService1/gajiviewResponse")]
        ClientGaji.ServiceReference1.gajiview[] gajiview();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/gajiview", ReplyAction="http://tempuri.org/IService1/gajiviewResponse")]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.gajiview[]> gajiviewAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (Gaji) of message GajiRequest does not match the default value (Gaji1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Gaji", ReplyAction="http://tempuri.org/IService1/GajiResponse")]
        ClientGaji.ServiceReference1.GajiResponse Gaji1(ClientGaji.ServiceReference1.GajiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Gaji", ReplyAction="http://tempuri.org/IService1/GajiResponse")]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.GajiResponse> Gaji1Async(ClientGaji.ServiceReference1.GajiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/gajiviewall", ReplyAction="http://tempuri.org/IService1/gajiviewallResponse")]
        ClientGaji.ServiceReference1.gajiviewall[] gajiviewall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/gajiviewall", ReplyAction="http://tempuri.org/IService1/gajiviewallResponse")]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.gajiviewall[]> gajiviewallAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        string Login(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        string Register(string username, string pass, string kategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string username, string pass, string kategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRegister", ReplyAction="http://tempuri.org/IService1/UpdateRegisterResponse")]
        string UpdateRegister(string username, string pass, string kategori, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRegister", ReplyAction="http://tempuri.org/IService1/UpdateRegisterResponse")]
        System.Threading.Tasks.Task<string> UpdateRegisterAsync(string username, string pass, string kategori, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRegister", ReplyAction="http://tempuri.org/IService1/DeleteRegisterResponse")]
        string DeleteRegister(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRegister", ReplyAction="http://tempuri.org/IService1/DeleteRegisterResponse")]
        System.Threading.Tasks.Task<string> DeleteRegisterAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataRegist", ReplyAction="http://tempuri.org/IService1/DataRegistResponse")]
        ClientGaji.ServiceReference1.DataRegister[] DataRegist();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataRegist", ReplyAction="http://tempuri.org/IService1/DataRegistResponse")]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.DataRegister[]> DataRegistAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Golongan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GolonganRequest {
        
        public GolonganRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GolonganResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GolonganResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ClientGaji.ServiceReference1.Golongan[] GolonganResult;
        
        public GolonganResponse() {
        }
        
        public GolonganResponse(ClientGaji.ServiceReference1.Golongan[] GolonganResult) {
            this.GolonganResult = GolonganResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Karyawan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KaryawanRequest {
        
        public KaryawanRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KaryawanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KaryawanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ClientGaji.ServiceReference1.Karyawan[] KaryawanResult;
        
        public KaryawanResponse() {
        }
        
        public KaryawanResponse(ClientGaji.ServiceReference1.Karyawan[] KaryawanResult) {
            this.KaryawanResult = KaryawanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Hadir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HadirRequest {
        
        public HadirRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HadirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HadirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ClientGaji.ServiceReference1.Hadir[] HadirResult;
        
        public HadirResponse() {
        }
        
        public HadirResponse(ClientGaji.ServiceReference1.Hadir[] HadirResult) {
            this.HadirResult = HadirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gaji", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GajiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int nip;
        
        public GajiRequest() {
        }
        
        public GajiRequest(int nip) {
            this.nip = nip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GajiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GajiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ClientGaji.ServiceReference1.Gaji[] GajiResult;
        
        public GajiResponse() {
        }
        
        public GajiResponse(ClientGaji.ServiceReference1.Gaji[] GajiResult) {
            this.GajiResult = GajiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientGaji.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientGaji.ServiceReference1.IService1>, ClientGaji.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string jabatan(int idjabatan, string jabatan1, int gajipokok, int tjjabatan) {
            return base.Channel.jabatan(idjabatan, jabatan1, gajipokok, tjjabatan);
        }
        
        public System.Threading.Tasks.Task<string> jabatanAsync(int idjabatan, string jabatan, int gajipokok, int tjjabatan) {
            return base.Channel.jabatanAsync(idjabatan, jabatan, gajipokok, tjjabatan);
        }
        
        public string editjabatan(int idjabatan, string jabatan, int gajipokok, int tjjabatan) {
            return base.Channel.editjabatan(idjabatan, jabatan, gajipokok, tjjabatan);
        }
        
        public System.Threading.Tasks.Task<string> editjabatanAsync(int idjabatan, string jabatan, int gajipokok, int tjjabatan) {
            return base.Channel.editjabatanAsync(idjabatan, jabatan, gajipokok, tjjabatan);
        }
        
        public string deletejabatan(int idjabatan) {
            return base.Channel.deletejabatan(idjabatan);
        }
        
        public System.Threading.Tasks.Task<string> deletejabatanAsync(int idjabatan) {
            return base.Channel.deletejabatanAsync(idjabatan);
        }
        
        public ClientGaji.ServiceReference1.jabatanview[] jabatanview() {
            return base.Channel.jabatanview();
        }
        
        public System.Threading.Tasks.Task<ClientGaji.ServiceReference1.jabatanview[]> jabatanviewAsync() {
            return base.Channel.jabatanviewAsync();
        }
        
        public string golongan(int idgolongan, int golongan1, int tjkeluarga, int tjkesehatan, int uanglembur, int uangmakan) {
            return base.Channel.golongan(idgolongan, golongan1, tjkeluarga, tjkesehatan, uanglembur, uangmakan);
        }
        
        public System.Threading.Tasks.Task<string> golonganAsync(int idgolongan, int golongan, int tjkeluarga, int tjkesehatan, int uanglembur, int uangmakan) {
            return base.Channel.golonganAsync(idgolongan, golongan, tjkeluarga, tjkesehatan, uanglembur, uangmakan);
        }
        
        public string editgolongan(int idgolongan, int golongan, int tjkeluarga, int tjkesehatan, int uanglembur, int uangmakann) {
            return base.Channel.editgolongan(idgolongan, golongan, tjkeluarga, tjkesehatan, uanglembur, uangmakann);
        }
        
        public System.Threading.Tasks.Task<string> editgolonganAsync(int idgolongan, int golongan, int tjkeluarga, int tjkesehatan, int uanglembur, int uangmakann) {
            return base.Channel.editgolonganAsync(idgolongan, golongan, tjkeluarga, tjkesehatan, uanglembur, uangmakann);
        }
        
        public string deletegolongan(int idgolongan) {
            return base.Channel.deletegolongan(idgolongan);
        }
        
        public System.Threading.Tasks.Task<string> deletegolonganAsync(int idgolongan) {
            return base.Channel.deletegolonganAsync(idgolongan);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientGaji.ServiceReference1.GolonganResponse ClientGaji.ServiceReference1.IService1.Golongan1(ClientGaji.ServiceReference1.GolonganRequest request) {
            return base.Channel.Golongan1(request);
        }
        
        public ClientGaji.ServiceReference1.Golongan[] Golongan1() {
            ClientGaji.ServiceReference1.GolonganRequest inValue = new ClientGaji.ServiceReference1.GolonganRequest();
            ClientGaji.ServiceReference1.GolonganResponse retVal = ((ClientGaji.ServiceReference1.IService1)(this)).Golongan1(inValue);
            return retVal.GolonganResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.GolonganResponse> ClientGaji.ServiceReference1.IService1.Golongan1Async(ClientGaji.ServiceReference1.GolonganRequest request) {
            return base.Channel.Golongan1Async(request);
        }
        
        public System.Threading.Tasks.Task<ClientGaji.ServiceReference1.GolonganResponse> Golongan1Async() {
            ClientGaji.ServiceReference1.GolonganRequest inValue = new ClientGaji.ServiceReference1.GolonganRequest();
            return ((ClientGaji.ServiceReference1.IService1)(this)).Golongan1Async(inValue);
        }
        
        public string karyawan(int idkaryawan, int nip, string nama, string jeniskelamin, string alamat, int idjabatan, int idgolongan, string status) {
            return base.Channel.karyawan(idkaryawan, nip, nama, jeniskelamin, alamat, idjabatan, idgolongan, status);
        }
        
        public System.Threading.Tasks.Task<string> karyawanAsync(int idkaryawan, int nip, string nama, string jeniskelamin, string alamat, int idjabatan, int idgolongan, string status) {
            return base.Channel.karyawanAsync(idkaryawan, nip, nama, jeniskelamin, alamat, idjabatan, idgolongan, status);
        }
        
        public string editkaryawan(int idkaryawan, int nip, string nama, string jeniskelamin, string alamat, int idjabatan, int idgolongan, string status) {
            return base.Channel.editkaryawan(idkaryawan, nip, nama, jeniskelamin, alamat, idjabatan, idgolongan, status);
        }
        
        public System.Threading.Tasks.Task<string> editkaryawanAsync(int idkaryawan, int nip, string nama, string jeniskelamin, string alamat, int idjabatan, int idgolongan, string status) {
            return base.Channel.editkaryawanAsync(idkaryawan, nip, nama, jeniskelamin, alamat, idjabatan, idgolongan, status);
        }
        
        public string deletekaryawan(int idkaryawan) {
            return base.Channel.deletekaryawan(idkaryawan);
        }
        
        public System.Threading.Tasks.Task<string> deletekaryawanAsync(int idkaryawan) {
            return base.Channel.deletekaryawanAsync(idkaryawan);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientGaji.ServiceReference1.KaryawanResponse ClientGaji.ServiceReference1.IService1.Karyawan1(ClientGaji.ServiceReference1.KaryawanRequest request) {
            return base.Channel.Karyawan1(request);
        }
        
        public ClientGaji.ServiceReference1.Karyawan[] Karyawan1() {
            ClientGaji.ServiceReference1.KaryawanRequest inValue = new ClientGaji.ServiceReference1.KaryawanRequest();
            ClientGaji.ServiceReference1.KaryawanResponse retVal = ((ClientGaji.ServiceReference1.IService1)(this)).Karyawan1(inValue);
            return retVal.KaryawanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.KaryawanResponse> ClientGaji.ServiceReference1.IService1.Karyawan1Async(ClientGaji.ServiceReference1.KaryawanRequest request) {
            return base.Channel.Karyawan1Async(request);
        }
        
        public System.Threading.Tasks.Task<ClientGaji.ServiceReference1.KaryawanResponse> Karyawan1Async() {
            ClientGaji.ServiceReference1.KaryawanRequest inValue = new ClientGaji.ServiceReference1.KaryawanRequest();
            return ((ClientGaji.ServiceReference1.IService1)(this)).Karyawan1Async(inValue);
        }
        
        public string hadir(int idhadir, string bulan, int idkaryawan, int lembur, int masuk) {
            return base.Channel.hadir(idhadir, bulan, idkaryawan, lembur, masuk);
        }
        
        public System.Threading.Tasks.Task<string> hadirAsync(int idhadir, string bulan, int idkaryawan, int lembur, int masuk) {
            return base.Channel.hadirAsync(idhadir, bulan, idkaryawan, lembur, masuk);
        }
        
        public string edithadir(int idhadir, string bulan, int idkaryawan, int lembur, int masuk) {
            return base.Channel.edithadir(idhadir, bulan, idkaryawan, lembur, masuk);
        }
        
        public System.Threading.Tasks.Task<string> edithadirAsync(int idhadir, string bulan, int idkaryawan, int lembur, int masuk) {
            return base.Channel.edithadirAsync(idhadir, bulan, idkaryawan, lembur, masuk);
        }
        
        public string deletehadir(int idhadir) {
            return base.Channel.deletehadir(idhadir);
        }
        
        public System.Threading.Tasks.Task<string> deletehadirAsync(int idhadir) {
            return base.Channel.deletehadirAsync(idhadir);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientGaji.ServiceReference1.HadirResponse ClientGaji.ServiceReference1.IService1.Hadir1(ClientGaji.ServiceReference1.HadirRequest request) {
            return base.Channel.Hadir1(request);
        }
        
        public ClientGaji.ServiceReference1.Hadir[] Hadir1() {
            ClientGaji.ServiceReference1.HadirRequest inValue = new ClientGaji.ServiceReference1.HadirRequest();
            ClientGaji.ServiceReference1.HadirResponse retVal = ((ClientGaji.ServiceReference1.IService1)(this)).Hadir1(inValue);
            return retVal.HadirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.HadirResponse> ClientGaji.ServiceReference1.IService1.Hadir1Async(ClientGaji.ServiceReference1.HadirRequest request) {
            return base.Channel.Hadir1Async(request);
        }
        
        public System.Threading.Tasks.Task<ClientGaji.ServiceReference1.HadirResponse> Hadir1Async() {
            ClientGaji.ServiceReference1.HadirRequest inValue = new ClientGaji.ServiceReference1.HadirRequest();
            return ((ClientGaji.ServiceReference1.IService1)(this)).Hadir1Async(inValue);
        }
        
        public string gaji(int noslip, System.DateTime tanggal, int idhadir, int subtotal, int pph) {
            return base.Channel.gaji(noslip, tanggal, idhadir, subtotal, pph);
        }
        
        public System.Threading.Tasks.Task<string> gajiAsync(int noslip, System.DateTime tanggal, int idhadir, int subtotal, int pph) {
            return base.Channel.gajiAsync(noslip, tanggal, idhadir, subtotal, pph);
        }
        
        public string editgaji(int idgaji, int noslip, System.DateTime tanggal, int idhadir, int subtotal, int pph) {
            return base.Channel.editgaji(idgaji, noslip, tanggal, idhadir, subtotal, pph);
        }
        
        public System.Threading.Tasks.Task<string> editgajiAsync(int idgaji, int noslip, System.DateTime tanggal, int idhadir, int subtotal, int pph) {
            return base.Channel.editgajiAsync(idgaji, noslip, tanggal, idhadir, subtotal, pph);
        }
        
        public string deletegaji(int noslip) {
            return base.Channel.deletegaji(noslip);
        }
        
        public System.Threading.Tasks.Task<string> deletegajiAsync(int noslip) {
            return base.Channel.deletegajiAsync(noslip);
        }
        
        public ClientGaji.ServiceReference1.Gajisub[] Gajisub(int idhadir) {
            return base.Channel.Gajisub(idhadir);
        }
        
        public System.Threading.Tasks.Task<ClientGaji.ServiceReference1.Gajisub[]> GajisubAsync(int idhadir) {
            return base.Channel.GajisubAsync(idhadir);
        }
        
        public ClientGaji.ServiceReference1.gajiview[] gajiview() {
            return base.Channel.gajiview();
        }
        
        public System.Threading.Tasks.Task<ClientGaji.ServiceReference1.gajiview[]> gajiviewAsync() {
            return base.Channel.gajiviewAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientGaji.ServiceReference1.GajiResponse ClientGaji.ServiceReference1.IService1.Gaji1(ClientGaji.ServiceReference1.GajiRequest request) {
            return base.Channel.Gaji1(request);
        }
        
        public ClientGaji.ServiceReference1.Gaji[] Gaji1(int nip) {
            ClientGaji.ServiceReference1.GajiRequest inValue = new ClientGaji.ServiceReference1.GajiRequest();
            inValue.nip = nip;
            ClientGaji.ServiceReference1.GajiResponse retVal = ((ClientGaji.ServiceReference1.IService1)(this)).Gaji1(inValue);
            return retVal.GajiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientGaji.ServiceReference1.GajiResponse> ClientGaji.ServiceReference1.IService1.Gaji1Async(ClientGaji.ServiceReference1.GajiRequest request) {
            return base.Channel.Gaji1Async(request);
        }
        
        public System.Threading.Tasks.Task<ClientGaji.ServiceReference1.GajiResponse> Gaji1Async(int nip) {
            ClientGaji.ServiceReference1.GajiRequest inValue = new ClientGaji.ServiceReference1.GajiRequest();
            inValue.nip = nip;
            return ((ClientGaji.ServiceReference1.IService1)(this)).Gaji1Async(inValue);
        }
        
        public ClientGaji.ServiceReference1.gajiviewall[] gajiviewall() {
            return base.Channel.gajiviewall();
        }
        
        public System.Threading.Tasks.Task<ClientGaji.ServiceReference1.gajiviewall[]> gajiviewallAsync() {
            return base.Channel.gajiviewallAsync();
        }
        
        public string Login(string username, string pass) {
            return base.Channel.Login(username, pass);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string pass) {
            return base.Channel.LoginAsync(username, pass);
        }
        
        public string Register(string username, string pass, string kategori) {
            return base.Channel.Register(username, pass, kategori);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string username, string pass, string kategori) {
            return base.Channel.RegisterAsync(username, pass, kategori);
        }
        
        public string UpdateRegister(string username, string pass, string kategori, int id) {
            return base.Channel.UpdateRegister(username, pass, kategori, id);
        }
        
        public System.Threading.Tasks.Task<string> UpdateRegisterAsync(string username, string pass, string kategori, int id) {
            return base.Channel.UpdateRegisterAsync(username, pass, kategori, id);
        }
        
        public string DeleteRegister(string username) {
            return base.Channel.DeleteRegister(username);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRegisterAsync(string username) {
            return base.Channel.DeleteRegisterAsync(username);
        }
        
        public ClientGaji.ServiceReference1.DataRegister[] DataRegist() {
            return base.Channel.DataRegist();
        }
        
        public System.Threading.Tasks.Task<ClientGaji.ServiceReference1.DataRegister[]> DataRegistAsync() {
            return base.Channel.DataRegistAsync();
        }
    }
}
